---
# =============================================================================
# AUR Role â€” Variables
# =============================================================================

aur_helper: yay
aur_helper_url: "https://aur.archlinux.org/{{ aur_helper }}.git"
